### PR TITLE
Fix dropdown button knobs not working

### LINKED ISSUE #50: Knobs for Dropdown button not working in storybook
Note: This issue has to be worked on by an andculture employee since the styles will be ported from an internal project. 

The knobs for Dropdown button are not working in storybook. The button size and button style knobs are not reflected in the rendering of the dropdown when their values are changed. The styles can be ported from the fire/electrical codes project.

### PR DESCRIPTION
**Pull request by SaidShah**
- [x] Related GitHub issue(s) linked in PR description
- [x] Destination branch merged, built and tested with your changes
- [x] Code formatted and follows best practices and patterns
- [x] Code builds cleanly (no _additional_ warnings or errors)
- [x] Manually tested
- [x] Automated tests are passing
- [x] No _decreases_ in automated test coverage
- [x] Documentation updated (readme, docs, comments, etc.)
- [x] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
- [x] New component and/ or properties? Make sure to update storybook

Closes #50

### CODE REVIEW

File: src/molecules/dropdown-button/dropdown-button.tsx [hunk 1]
```diff
@@ -50,11 +50,11 @@ const DropdownButton: React.FC<DropdownButtonProps> = (
     }
 
     if (size != null) {
-        classNames.push(size);
+        classNames.push(`-${size}`);
```
Comment (brandongregoryscott) [inline src/molecules/dropdown-button/dropdown-button.tsx:53]: Were the `ButtonSize` and `ButtonStyle` enums changed? Just curious about this - not saying it should change back, if so. I believe we have been trying to move away from coupling the class name to the enum representation

**Review by brandongregoryscott — APPROVED** [review]

File: src/molecules/dropdown-button/dropdown-button.tsx (hunk 1 above)
Comment (SaidShah) [reply src/molecules/dropdown-button/dropdown-button.tsx:53]: No the `ButtonSize` and `ButtonStyle` enums were not changed. They are being used in many places but the issue was all the other places were using `(`-${size}`)` as opposed to `(size)`, and same goes for style. That is also how they are being given styles through the CSS.

**Comment by brandongregoryscott** [comment]
Pulled it down & gave it a whirl - the described issue is fixed, but we may need to revisit the actual styles. The dropdown looks a bit silly in pretty much every state - 

- Small
image
- Medium
image
- Large
image
